"""Core domain models for Aurel2."""

from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from enum import Enum


class AssetCategory(str, Enum):
    """Broad asset categories."""
    EQUITY = "equity"
    FIXED_INCOME = "fixed_income"
    ALTERNATIVE = "alternative"
    CASH = "cash"


class AssetClass(str, Enum):
    """Asset classes for momentum strategy."""
    # Core Equity
    US_STOCKS = "us_stocks"
    INTL_DEVELOPED = "intl_developed"
    EMERGING_MARKETS = "emerging_markets"
    # Sectors
    TECH_SECTOR = "tech_sector"
    FINANCIAL_SECTOR = "financial_sector"
    ENERGY_SECTOR = "energy_sector"
    HEALTHCARE_SECTOR = "healthcare_sector"
    # Fixed Income
    BONDS_AGGREGATE = "bonds_aggregate"
    BONDS_TREASURY = "bonds_treasury"
    BONDS_SHORT_TERM = "bonds_short_term"
    BONDS_INTERMEDIATE = "bonds_intermediate"
    TIPS = "tips"
    # Real Assets
    REITS = "reits"
    # Alternatives
    GOLD = "gold"
    COMMODITIES = "commodities"
    # Size/Style
    SMALL_CAP_VALUE = "small_cap_value"
    # Cash
    CASH = "cash"
    # Backward compatibility aliases
    GLOBAL_STOCKS = "intl_developed"  # Alias for INTL_DEVELOPED
    BONDS = "bonds_aggregate"  # Alias for BONDS_AGGREGATE


class SignalAction(str, Enum):
    """Trading signal actions."""
    HOLD = "hold"
    BUY = "buy"
    SELL = "sell"


@dataclass(frozen=True)
class Asset:
    """An investable asset."""
    symbol: str
    name: str
    asset_class: AssetClass
    isin: str | None = None
    yahoo_symbol: str | None = None
    category: AssetCategory = AssetCategory.EQUITY
    ucits_symbol: str | None = None


@dataclass
class MomentumScore:
    """Momentum score for an asset at a point in time."""
    asset: Asset
    date: date
    momentum_12m: float  # 12-month return
    price: float
    price_12m_ago: float

    @property
    def is_positive(self) -> bool:
        """True if momentum is positive (beating cash at 0%)."""
        return self.momentum_12m > 0


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    date: date
    action: SignalAction
    asset: Asset
    reason: str
    momentum_scores: dict[AssetClass, MomentumScore]

    @property
    def winner(self) -> MomentumScore | None:
        """The highest momentum asset."""
        if not self.momentum_scores:
            return None
        return max(self.momentum_scores.values(), key=lambda m: m.momentum_12m)


@dataclass
class Position:
    """A portfolio position."""
    asset: Asset
    shares: Decimal
    entry_price: float
    entry_date: date
    current_price: float | None = None

    @property
    def market_value(self) -> Decimal:
        """Current market value."""
        price = self.current_price or self.entry_price
        return self.shares * Decimal(str(price))

    @property
    def unrealized_pnl(self) -> float:
        """Unrealized profit/loss."""
        if self.current_price is None:
            return 0.0
        return float(self.shares) * (self.current_price - self.entry_price)

    @property
    def unrealized_pnl_pct(self) -> float:
        """Unrealized P&L as percentage."""
        if self.entry_price == 0:
            return 0.0
        return (self.current_price or self.entry_price) / self.entry_price - 1


@dataclass
class Trade:
    """A completed trade."""
    date: date
    asset: Asset
    action: SignalAction
    shares: Decimal
    price: float
    commission: float = 0.0

    @property
    def value(self) -> float:
        """Total trade value (excluding commission)."""
        return float(self.shares) * self.price

    @property
    def total_cost(self) -> float:
        """Total cost including commission."""
        return self.value + self.commission


@dataclass
class PortfolioSnapshot:
    """Portfolio state at a point in time."""
    date: date
    cash: Decimal
    positions: list[Position]
    total_value: Decimal
    holding_symbol: str | None = None
    holding_asset_class: AssetClass | None = None

    @property
    def position_value(self) -> Decimal:
        """Total value of all positions."""
        return sum((p.market_value for p in self.positions), Decimal("0"))
