#!/usr/bin/env python3
"""Regime-gate backtest matrix for the Phase 2 deterministic-core decision.

Contenders:
  1. a2_baseline        - A2's live config exactly as a2_replay.py wires it.
  2. a2_gate_lt         - a2_baseline + regime gate, detector = LT-heuristic
                          (infer_regime, adapted from live-trader's daily_runner.py).
  3. a2_gate_trendvol   - a2_baseline + regime gate, detector = SPY 200dma + realized-vol percentile.
  4. a2_gate_hmm        - a2_baseline + regime gate, detector = walk-forward 2-state Gaussian HMM on SPY returns.
  5. spy_buyhold, qqq_buyhold - controls.

The gate mechanism (identical across detectors 2-4, only the detector state differs):
  risk_off -> equity_to_defensive=0.02, defensive_to_equity=0.15 (easy out, hard back in)
  risk_on  -> equity_to_defensive=0.15, defensive_to_equity=0.05 (live defaults)
  mixed    -> hold previous day's gate state (hysteresis)

No src/aurel2/ source is modified. The gate mutates DualMomentumStrategy's threshold
attributes in-place, day-by-day, before each generate_signal() call — same pattern
a2_replay.py uses to drive the engine, just with thresholds swapped per day.

Output: data/edge_decomposition/regime_gate_matrix.json
"""

from __future__ import annotations

import multiprocessing as mp
import sys
import time
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

import structlog
structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(50))
import logging
logging.disable(logging.CRITICAL)

import json
from decimal import Decimal

import numpy as np
import pandas as pd
import yfinance as yf

from aurel2.core.assets import ASSET_REGISTRY, get_all_yahoo_symbols
from aurel2.core.models import AssetClass, SignalAction
from aurel2.data.providers.cache import CachedPriceProvider
from aurel2.engine.backtest import BacktestEngine
from aurel2.strategies.dual_momentum import DualMomentumStrategy

OUT_PATH = REPO_ROOT / "data" / "edge_decomposition" / "regime_gate_matrix.json"

# --- Windows ---
WINDOWS = {
    "2026_decomposition": (date(2026, 2, 11), date(2026, 7, 8)),
    "5y": (date(2021, 7, 1), date(2026, 7, 8)),
    "full_15y": (date(2010, 1, 1), date(2026, 2, 1)),
    "rate_hike_bear_2022": (date(2022, 1, 1), date(2022, 12, 31)),
    "covid_v_2020": (date(2020, 3, 23), date(2022, 1, 1)),
    "ai_bull_2023": (date(2023, 1, 1), date(2026, 2, 1)),
}
# Earliest data needed across all windows, with slack for 12m momentum + 200dma/HMM warmup.
FETCH_START = date(2008, 1, 1)
FETCH_END = max(end for _, end in WINDOWS.values())

# Live default gate thresholds (A2-baseline, no gate).
LIVE_EQ_TO_DEF = 0.15
LIVE_DEF_TO_EQ = 0.05
# Gated thresholds when regime = risk_off: easy out of equity, hard back in.
GATED_EQ_TO_DEF = 0.02
GATED_DEF_TO_EQ = 0.15

NOTES: list[str] = [
    "SANITY CHECK CORRECTION: the task brief's full_15y sanity target (~10.4% CAGR, from "
    "lookback_and_vote_2026_07_07.json's 12m row) turned out to be generated by a DIFFERENT "
    "config than a2_baseline (scripts/backtest_lookback.py uses full ASSET_REGISTRY with TLT "
    "included and default switch_threshold=0.04, vs a2_baseline's no-TLT universe and "
    "switch_threshold=0.02) -- not a valid comparison. Investigated and replaced with "
    "data/backtest_comparison.json's '15y' entry, which is explicitly the same config as "
    "a2_baseline (strategy label DM_NO_TLT_daily_no_calm_no_minhold, 2010-01-01 start): "
    "CAGR=15.7% over 2010-01-01..2026-06-11. a2_baseline's actual full_15y run (2010-01-01.."
    "2026-02-01, ~4mo shorter) landed at CAGR~15.0%, consistent with that reference.",
]


# ============================================================================
# Detector 1: LT-heuristic (adapted from live-trader/daily_runner.py infer_regime)
# ============================================================================
# Adapted from /Users/claudiu/.openclaw/workspace/live-trader/daily_runner.py
# (READ-ONLY dir; logic copied, not imported, since that module pulls in
# broker-dependent imports at load time). Original breadth/trend/gold-leadership
# heuristic over RISK_ASSETS = {SPY, QQQ, IWM, EFA, EEM, XLE}, DEFENSIVE = {GLD, TLT}.
# Here narrowed to the SPY/QQQ/GLD subset this script fetches (all three are in
# the original RISK_ASSETS/DEFENSIVE sets), which changes the breadth denominator
# from 6 risk assets to 2 (SPY, QQQ) — documented as a fidelity caveat below.
LT_RISK_ASSETS = ("SPY", "QQQ")
LT_DEFENSIVE = ("GLD",)


def lt_heuristic_regime(ret20: dict[str, float]) -> str:
    """ret20: {"SPY": .., "QQQ": .., "GLD": ..} 20-trading-day returns through prior close."""
    risk_positive = sum(1 for s in LT_RISK_ASSETS if ret20.get(s, 0.0) > 0)
    breadth = risk_positive / len(LT_RISK_ASSETS)
    spy20 = ret20.get("SPY", 0.0)
    qqq20 = ret20.get("QQQ", 0.0)
    gld20 = ret20.get("GLD", 0.0)

    risk_on = breadth >= 0.55 and (spy20 > 0 or qqq20 > 0)
    risk_off = breadth <= 0.30 and gld20 > 0

    if risk_off:
        return "risk_off"
    elif risk_on:
        return "risk_on"
    return "mixed"


# ============================================================================
# Detector 2: trend-vol (SPY 200dma + realized-vol percentile)
# ============================================================================
def trendvol_regime(spy_close: float, sma200: float | None, vol20: float | None, vol_pct80: float | None) -> str:
    if sma200 is None:
        return "mixed"
    if spy_close < sma200 and vol20 is not None and vol_pct80 is not None and vol20 > vol_pct80:
        return "risk_off"
    if spy_close > sma200:
        return "risk_on"
    return "mixed"


# ============================================================================
# Detector 3: walk-forward 2-state Gaussian HMM on SPY daily returns
# ============================================================================
# Integrity: state inference for day D uses a model fit only on returns through
# day D-1's close, and only infers using return history through D-1 as well
# (the return "on day D" is not known until D's close, which is also the price
# used to execute D's trade — so even the feature itself must stop at D-1).
# Refit is monthly (first trading day seen of each new calendar month) using an
# expanding window from FETCH_START through the most recently completed prior
# trading day. Between refits, the previously-fit model is reused for daily
# state inference. This guarantees no future data ever enters a decision.
@dataclass
class HMMWalkForward:
    returns: pd.Series  # SPY daily log returns, indexed by date
    _model: object = field(default=None, repr=False)
    _last_refit_month: tuple[int, int] | None = field(default=None, repr=False)
    _risk_off_state: int | None = field(default=None, repr=False)
    refits: int = 0

    def _refit(self, as_of_idx: int):
        from hmmlearn.hmm import GaussianHMM

        train = self.returns.iloc[:as_of_idx].values.reshape(-1, 1)
        if len(train) < 60:
            self._model = None
            return
        model = GaussianHMM(n_components=2, covariance_type="diag", n_iter=100, random_state=42)
        try:
            model.fit(train)
        except Exception:
            self._model = None
            return
        # Identify the risk_off state as the one with lower mean return (ties: higher variance).
        means = model.means_.flatten()
        variances = np.array([np.diag(c)[0] for c in model.covars_]) if model.covariance_type != "diag" else model.covars_.flatten()
        risk_off_state = int(np.argmin(means))
        self._model = model
        self._risk_off_state = risk_off_state
        self.refits += 1

    def state_for(self, d: date) -> str:
        """Regime for day d, using only returns through d's index minus 1 for the training
        cutoff, and returns through d's index minus 1 for inference too (see class docstring).
        """
        if d not in self.returns.index:
            return "mixed"
        idx = self.returns.index.get_loc(d)
        if idx < 60:
            return "mixed"

        month_key = (d.year, d.month)
        if self._last_refit_month != month_key:
            self._refit(idx)  # train on returns[:idx] -> strictly before day d
            self._last_refit_month = month_key

        if self._model is None:
            return "mixed"

        infer_window = self.returns.iloc[:idx].values.reshape(-1, 1)  # strictly before d
        if len(infer_window) < 2:
            return "mixed"
        try:
            states = self._model.predict(infer_window)
        except Exception:
            return "mixed"
        current_state = states[-1]
        return "risk_off" if current_state == self._risk_off_state else "risk_on"


# ============================================================================
# Data fetching
# ============================================================================
def fetch_regime_inputs() -> pd.DataFrame:
    """SPY/QQQ/GLD daily auto-adjusted closes, FETCH_START -> FETCH_END, as a wide DataFrame indexed by date."""
    print(f"Fetching SPY/QQQ/GLD {FETCH_START} -> {FETCH_END} for regime detectors...", file=sys.stderr)
    raw = yf.download(
        ["SPY", "QQQ", "GLD"], start=FETCH_START.isoformat(),
        end=(FETCH_END + timedelta(days=3)).isoformat(),
        auto_adjust=True, progress=False, group_by="ticker",
    )
    cols = {}
    for sym in ["SPY", "QQQ", "GLD"]:
        cols[sym] = raw[sym]["Close"].dropna()
    df = pd.DataFrame(cols)
    df.index = pd.to_datetime(df.index).date
    df = df.sort_index()
    return df


def build_gate_state_series(regime_df: pd.DataFrame) -> dict[str, dict[date, dict]]:
    """Precompute, for every trading day in regime_df, each detector's raw regime label.
    Strictly point-in-time: label for day D only uses data through D-1's close.
    Returns {detector_name: {date: {"regime": ..., diagnostics...}}}.
    """
    dates = list(regime_df.index)
    out: dict[str, dict[date, dict]] = {"lt_heuristic": {}, "trend_vol": {}, "hmm": {}}

    ret20 = regime_df.pct_change(20)
    sma200 = regime_df["SPY"].rolling(200).mean()
    daily_ret = regime_df["SPY"].pct_change()
    vol20 = daily_ret.rolling(20).std() * np.sqrt(252)
    # Trailing 1y (252 trading day) 80th percentile of the vol20 series, expanding-window
    # equivalent computed via rolling window so it's also strictly backward-looking.
    vol_pct80 = vol20.rolling(252, min_periods=60).quantile(0.80)

    log_ret = np.log(regime_df["SPY"] / regime_df["SPY"].shift(1))
    hmm_returns = log_ret.dropna()
    hmm = HMMWalkForward(returns=hmm_returns)

    for i, d in enumerate(dates):
        if i == 0:
            continue
        prev_d = dates[i - 1]

        # --- LT-heuristic: uses ret20 as of prev_d (data through prev close) ---
        r = ret20.loc[prev_d] if prev_d in ret20.index else None
        if r is not None and not r.isna().any():
            regime = lt_heuristic_regime({"SPY": r["SPY"], "QQQ": r["QQQ"], "GLD": r["GLD"]})
        else:
            regime = "mixed"
        out["lt_heuristic"][d] = {"regime": regime}

        # --- trend-vol: SPY close, 200dma, vol20, vol_pct80 all as of prev_d ---
        spy_prev = regime_df["SPY"].get(prev_d)
        sma_prev = sma200.get(prev_d)
        vol_prev = vol20.get(prev_d)
        volpct_prev = vol_pct80.get(prev_d)
        if spy_prev is not None and not pd.isna(spy_prev) and sma_prev is not None and not pd.isna(sma_prev):
            regime = trendvol_regime(
                spy_prev, sma_prev,
                None if vol_prev is None or pd.isna(vol_prev) else vol_prev,
                None if volpct_prev is None or pd.isna(volpct_prev) else volpct_prev,
            )
        else:
            regime = "mixed"
        out["trend_vol"][d] = {"regime": regime}

        # --- hmm: walk-forward, refit monthly, inference strictly through prev_d ---
        regime = hmm.state_for(d)
        out["hmm"][d] = {"regime": regime}

    NOTES.append(f"HMM walk-forward: {hmm.refits} monthly refits performed over {FETCH_START}..{FETCH_END}.")
    return out


# ============================================================================
# Gate wrapper: turns a detector's raw per-day regime into a hysteresis-applied
# gate state, and applies the corresponding thresholds to the strategy object.
# ============================================================================
class RegimeGate:
    def __init__(self, detector_series: dict[date, dict] | None):
        self.detector_series = detector_series  # None => no gate (a2_baseline)
        self.prev_gate_state = "risk_on"  # default start state
        self.episodes: list[dict] = []  # risk_off episodes: {"start": ..., "end": ...}
        self._current_episode_start: date | None = None
        self.days_risk_off = 0
        self.history: list[dict] = []

    def apply(self, strategy: DualMomentumStrategy, d: date):
        if self.detector_series is None:
            strategy.equity_to_defensive_threshold = LIVE_EQ_TO_DEF
            strategy.defensive_to_equity_threshold = LIVE_DEF_TO_EQ
            return "risk_on"

        raw = self.detector_series.get(d, {"regime": "mixed"})["regime"]
        if raw == "mixed":
            gate_state = self.prev_gate_state  # hysteresis
        else:
            gate_state = raw

        if gate_state == "risk_off":
            strategy.equity_to_defensive_threshold = GATED_EQ_TO_DEF
            strategy.defensive_to_equity_threshold = GATED_DEF_TO_EQ
            self.days_risk_off += 1
            if self._current_episode_start is None:
                self._current_episode_start = d
        else:
            strategy.equity_to_defensive_threshold = LIVE_EQ_TO_DEF
            strategy.defensive_to_equity_threshold = LIVE_DEF_TO_EQ
            if self._current_episode_start is not None:
                self.episodes.append({"start": self._current_episode_start.isoformat(), "end": d.isoformat()})
                self._current_episode_start = None

        self.history.append({"date": d.isoformat(), "raw_regime": raw, "gate_state": gate_state})
        self.prev_gate_state = gate_state
        return gate_state

    def finalize(self, last_date: date):
        if self._current_episode_start is not None:
            self.episodes.append({"start": self._current_episode_start.isoformat(), "end": last_date.isoformat()})
            self._current_episode_start = None

    def diagnostics(self) -> dict:
        return {
            "n_risk_off_episodes": len(self.episodes),
            "total_days_risk_off": self.days_risk_off,
            "risk_off_episodes": self.episodes,
        }


# ============================================================================
# Engine construction (mirrors a2_replay.build_live_engine exactly)
# ============================================================================
def build_engine() -> BacktestEngine:
    no_tlt_assets = {ac: a for ac, a in ASSET_REGISTRY.items() if ac != AssetClass.BONDS_TREASURY}
    engine = BacktestEngine(initial_capital=100.0, use_ai=False, correlation_guard=False, sideways_hold=False)
    engine.dual_momentum = DualMomentumStrategy(
        assets=no_tlt_assets,
        lookback_months=12,
        switch_threshold=0.02,
        cash_rate=0.0,
    )
    return engine


def run_contender(
    prices: pd.DataFrame,
    start: date,
    end: date,
    gate_detector_series: dict[date, dict] | None,
) -> dict:
    """Runs the a2_replay day-by-day loop (verbatim bookkeeping pattern) over [start, end],
    applying the gate's thresholds to engine.dual_momentum before each day's decision.
    """
    engine = build_engine()
    gate = RegimeGate(gate_detector_series)

    rebalance_dates = engine.dual_momentum.get_rebalance_dates(start, end, "daily")

    decisions = []
    daily_equity = []
    cash = Decimal("100.0")
    current_holding: AssetClass | None = None
    current_holding_symbol: str | None = None
    current_shares = Decimal("0")
    last_switch_date = None
    n_trades = 0

    def get_price(symbol: str, as_of: date) -> float | None:
        return engine._get_price(prices, symbol, as_of)

    for rebal_date in rebalance_dates:
        gate_state = gate.apply(engine.dual_momentum, rebal_date)

        signals = {}
        for name, strategy in [
            ("dual_momentum", engine.dual_momentum),
            ("mean_reversion", engine.mean_reversion),
            ("multi_timeframe", engine.multi_timeframe),
        ]:
            try:
                sig = strategy.generate_signal(prices=prices, calc_date=rebal_date, current_holding=current_holding)
                signals[name] = engine._normalize_signal(sig)
            except Exception as e:
                signals[name] = {"action": "hold", "confidence": 0.0, "error": str(e)}

        market_context = engine._build_market_context(prices, rebal_date)
        if last_switch_date is not None:
            market_context["days_since_last_switch"] = (rebal_date - last_switch_date).days

        decision = engine.orchestrator.analyze(
            signals=signals, market_context=market_context, current_holding=current_holding_symbol,
        )

        action = decision.action
        target_symbol = decision.asset_symbol
        position_size_pct = decision.position_size_pct

        trade_happened = False
        if action == SignalAction.BUY and target_symbol:
            target_asset_class = engine._symbol_to_asset_class(target_symbol)
            target_asset = engine._asset_for_class(target_asset_class) if target_asset_class else None

            if current_holding_symbol == target_symbol and current_shares > 0:
                pass
            elif target_asset_class == AssetClass.CASH:
                if current_holding and current_shares > 0:
                    held_asset = engine._asset_for_class(current_holding)
                    held_symbol = (held_asset.yahoo_symbol or held_asset.symbol) if held_asset else None
                    sell_price = get_price(held_symbol, rebal_date) if held_symbol else None
                    if sell_price:
                        sell_value = float(current_shares) * sell_price
                        commission = sell_value * engine.transaction_cost_pct
                        cash += Decimal(str(sell_value - commission))
                        current_shares = Decimal("0")
                current_holding = AssetClass.CASH
                current_holding_symbol = "CASH"
                last_switch_date = rebal_date
                trade_happened = True
            elif target_asset and target_asset.yahoo_symbol:
                buy_price = get_price(target_asset.yahoo_symbol, rebal_date)
                if buy_price:
                    if current_holding and current_holding != AssetClass.CASH and current_shares > 0:
                        old_asset = engine._asset_for_class(current_holding) or ASSET_REGISTRY[current_holding]
                        sell_price = get_price(old_asset.yahoo_symbol or old_asset.symbol, rebal_date)
                        if sell_price:
                            sell_value = float(current_shares) * sell_price
                            commission = sell_value * engine.transaction_cost_pct
                            cash += Decimal(str(sell_value - commission))
                            current_shares = Decimal("0")
                    buy_value = float(cash) * position_size_pct
                    remaining_cash = float(cash) - buy_value
                    commission = buy_value * engine.transaction_cost_pct
                    net_value = buy_value - commission
                    shares_to_buy = Decimal(str(net_value / buy_price))
                    cash = Decimal(str(remaining_cash))
                    current_shares = shares_to_buy
                    current_holding = target_asset_class
                    current_holding_symbol = target_symbol
                    last_switch_date = rebal_date
                    trade_happened = True
        elif action == SignalAction.SELL:
            if current_holding and current_holding != AssetClass.CASH and current_shares > 0:
                old_asset = engine._asset_for_class(current_holding) or ASSET_REGISTRY[current_holding]
                sell_price = get_price(old_asset.yahoo_symbol or old_asset.symbol, rebal_date)
                if sell_price:
                    sell_value = float(current_shares) * sell_price
                    commission = sell_value * engine.transaction_cost_pct
                    cash += Decimal(str(sell_value - commission))
                    current_shares = Decimal("0")
                    current_holding = AssetClass.CASH
                    current_holding_symbol = "CASH"
                    trade_happened = True

        if trade_happened:
            n_trades += 1

        current_price = None
        if current_holding and current_holding != AssetClass.CASH and current_shares > 0:
            held_asset = engine._asset_for_class(current_holding)
            if held_asset and held_asset.yahoo_symbol:
                current_price = get_price(held_asset.yahoo_symbol, rebal_date)

        total_value = float(current_shares) * current_price + float(cash) if current_price and current_shares > 0 else float(cash)

        decisions.append({
            "date": rebal_date.isoformat(), "action": action.value, "symbol": target_symbol,
            "gate_state": gate_state,
        })
        daily_equity.append({
            "date": rebal_date.isoformat(), "equity": round(total_value, 6),
            "holding": current_holding_symbol or "CASH",
        })

    gate.finalize(rebalance_dates[-1] if rebalance_dates else end)

    return {
        "daily_equity": daily_equity,
        "decisions": decisions,
        "n_trades": n_trades,
        "gate_diagnostics": gate.diagnostics() if gate_detector_series is not None else None,
        "gate_history": gate.history if gate_detector_series is not None else None,
    }


# ============================================================================
# Metrics (mirrors BacktestEngine.calculate_metrics conventions)
# ============================================================================
def calc_metrics(daily_equity: list[dict], start: date, end: date) -> dict:
    if not daily_equity:
        return {"cagr": 0.0, "total_return": 0.0, "max_drawdown": 0.0, "sharpe": 0.0, "n_trades": 0}

    values = [d["equity"] for d in daily_equity]
    initial = 100.0
    final = values[-1]

    total_return = (final / initial) - 1

    years = (end - start).days / 365.25
    cagr = (final / initial) ** (1 / years) - 1 if years > 0 else 0.0

    peak = values[0]
    max_dd = 0.0
    for v in values:
        if v > peak:
            peak = v
        dd = (peak - v) / peak
        if dd > max_dd:
            max_dd = dd

    periods_per_year = (len(values) - 1) / years if years > 0 and len(values) > 1 else 252
    sharpe = 0.0
    if len(values) > 1:
        returns = pd.Series(values).pct_change().dropna()
        if len(returns) > 0 and returns.std() > 0:
            sharpe = (returns.mean() * periods_per_year) / (returns.std() * np.sqrt(periods_per_year))

    return {
        "cagr": round(cagr, 6),
        "total_return": round(total_return, 6),
        "max_drawdown": round(max_dd, 6),
        "sharpe": round(float(sharpe), 6),
        "final_equity": round(final, 4),
    }


def buyhold_metrics(prices: pd.DataFrame, symbol: str, start: date, end: date) -> dict:
    sym_prices = prices[prices["symbol"] == symbol].copy()
    sym_prices["date"] = pd.to_datetime(sym_prices["date"])
    window = sym_prices[(sym_prices["date"] >= pd.Timestamp(start)) & (sym_prices["date"] <= pd.Timestamp(end))].sort_values("date")
    if window.empty:
        return {"cagr": 0.0, "total_return": 0.0, "max_drawdown": 0.0, "sharpe": 0.0}
    daily_equity = [{"date": r["date"].date().isoformat(), "equity": 100.0 * (r["close"] / window.iloc[0]["close"])} for _, r in window.iterrows()]
    return calc_metrics(daily_equity, start, end)


def buyhold_metrics_from_closes(closes: pd.Series, start: date, end: date) -> dict:
    """Same as buyhold_metrics but for a plain date-indexed close-price Series
    (used for QQQ, which is not in aurel2's ASSET_REGISTRY / prices frame)."""
    window = closes[(closes.index >= start) & (closes.index <= end)].sort_index()
    if window.empty:
        return {"cagr": 0.0, "total_return": 0.0, "max_drawdown": 0.0, "sharpe": 0.0}
    daily_equity = [{"date": d.isoformat(), "equity": 100.0 * (v / window.iloc[0])} for d, v in window.items()]
    return calc_metrics(daily_equity, start, end)


# ============================================================================
# Detection-lag diagnostics: when did each gated detector first flip risk_off
# relative to the actual drawdown start of the 2022 bear and COVID crash?
# ============================================================================
def detection_lag(gate_history: list[dict] | None, drawdown_start: date, window_end: date) -> dict | None:
    if not gate_history:
        return None
    trading_days = [pd.Timestamp(h["date"]).date() for h in gate_history]
    first_risk_off = next((h["date"] for h in gate_history if h["gate_state"] == "risk_off" and h["date"] >= drawdown_start.isoformat()), None)
    if first_risk_off is None:
        return {"detected": False, "note": "never entered risk_off gate state in this window"}
    detect_date = date.fromisoformat(first_risk_off)
    lag_days = sum(1 for d in trading_days if drawdown_start <= d < detect_date)
    return {"detected": True, "drawdown_start": drawdown_start.isoformat(), "detection_date": first_risk_off, "lag_trading_days": lag_days}


def _run_one(args) -> tuple[str, str, dict]:
    """Top-level (picklable) worker for one (contender, window) cell."""
    cname, window_name, prices, regime_df, start, end, gseries = args
    wt0 = time.time()

    spy_m = buyhold_metrics(prices, "SPY", start, end)
    qqq_m = buyhold_metrics_from_closes(regime_df["QQQ"], start, end)

    run = run_contender(prices, start, end, gseries)
    m = calc_metrics(run["daily_equity"], start, end)
    m["switches"] = run["n_trades"]
    m["alpha_vs_spy"] = round(m["cagr"] - spy_m["cagr"], 6)
    m["alpha_vs_qqq"] = round(m["cagr"] - qqq_m["cagr"], 6)
    if run["gate_diagnostics"] is not None:
        m["gate_diagnostics"] = run["gate_diagnostics"]
        if window_name == "rate_hike_bear_2022":
            m["detection_lag"] = detection_lag(run["gate_history"], date(2022, 1, 3), end)
        elif window_name == "covid_v_2020":
            # COVID crash proper started 2020-02-19; this window starts mid-recovery
            # (2020-03-23), so lag diagnostics here measure re-entry to risk_on speed
            # instead of crash detection. Noted below.
            m["detection_lag"] = detection_lag(run["gate_history"], date(2020, 3, 23), end)

    print(f"  [{window_name}] {cname}: CAGR={m['cagr']:.2%} maxDD={m['max_drawdown']:.2%} "
          f"sharpe={m['sharpe']:.2f} switches={m['switches']} ({time.time()-wt0:.0f}s)", file=sys.stderr)
    return cname, window_name, m


def run_sanity_checks(prices: pd.DataFrame, regime_df: pd.DataFrame) -> bool:
    """A2-baseline only, on the two windows with known reference numbers.
    Returns True if both are within tolerance."""
    ok = True

    start, end = WINDOWS["2026_decomposition"]
    run = run_contender(prices, start, end, None)
    m = calc_metrics(run["daily_equity"], start, end)
    expected_tr = 0.121  # a2_replay.json / task brief: ~+12.1% total return
    if abs(m["total_return"] - expected_tr) > 0.01:
        print(f"SANITY FAIL: 2026_decomposition total_return={m['total_return']:.4f}, expected ~{expected_tr}", file=sys.stderr)
        ok = False
    else:
        print(f"SANITY OK: 2026_decomposition total_return={m['total_return']:.4f} (expected ~{expected_tr})", file=sys.stderr)

    start, end = WINDOWS["full_15y"]
    run = run_contender(prices, start, end, None)
    m = calc_metrics(run["daily_equity"], start, end)
    # Task brief cited lookback_and_vote_2026_07_07.json's 12m row (~10.4% CAGR) as the
    # full_15y target, but that sweep (scripts/backtest_lookback.py) uses a DIFFERENT
    # config than a2_baseline: full ASSET_REGISTRY (TLT included) and switch_threshold=0.04
    # default, vs a2_baseline's no-TLT universe and switch_threshold=0.02. Not comparable.
    # The correct same-config reference is data/backtest_comparison.json's "15y" entry
    # (strategy="DM_NO_TLT_daily_no_calm_no_minhold", 2010-01-01 start, matches a2_baseline
    # exactly): CAGR=15.7% over 2010-01-01..2026-06-11. Our window ends 2026-02-01 (~4mo
    # earlier), so exact match isn't expected, but it should land in the same neighborhood.
    expected_cagr = 0.157  # data/backtest_comparison.json "15y" (same config as a2_baseline)
    if abs(m["cagr"] - expected_cagr) > 0.03:
        print(f"SANITY FAIL: full_15y CAGR={m['cagr']:.4f}, expected ~{expected_cagr}", file=sys.stderr)
        ok = False
    else:
        print(f"SANITY OK: full_15y CAGR={m['cagr']:.4f} (expected ~{expected_cagr}, from backtest_comparison.json's same-config 15y run)", file=sys.stderr)

    return ok


def main():
    t0 = time.time()
    provider = CachedPriceProvider()
    symbols = get_all_yahoo_symbols()
    if "SPY" not in symbols:
        symbols.append("SPY")

    print(f"Fetching {len(symbols)} symbols {FETCH_START} -> {FETCH_END}...", file=sys.stderr)
    prices = provider.get_multi_prices(symbols, FETCH_START, FETCH_END)
    if prices.empty:
        print("ERROR: no price data", file=sys.stderr)
        sys.exit(1)
    t_fetch_prices = time.time() - t0
    print(f"{len(prices)} price rows fetched ({t_fetch_prices:.0f}s)", file=sys.stderr)

    t1 = time.time()
    regime_df = fetch_regime_inputs()
    t_fetch_regime = time.time() - t1
    print(f"Regime inputs fetched ({t_fetch_regime:.0f}s). Building detector state series (HMM walk-forward is the slow part)...", file=sys.stderr)

    t2 = time.time()
    detector_series = build_gate_state_series(regime_df)
    t_detectors = time.time() - t2
    print(f"Detector series built ({t_detectors:.0f}s).", file=sys.stderr)

    print("\n=== Sanity checks (A2-baseline only) ===", file=sys.stderr)
    t3 = time.time()
    if not run_sanity_checks(prices, regime_df):
        print("ERROR: sanity checks failed, aborting before full grid.", file=sys.stderr)
        sys.exit(1)
    t_sanity = time.time() - t3

    contenders = {
        "a2_baseline": None,
        "a2_gate_lt": detector_series["lt_heuristic"],
        "a2_gate_trendvol": detector_series["trend_vol"],
        "a2_gate_hmm": detector_series["hmm"],
    }

    results: dict[str, dict] = {c: {} for c in contenders}
    results["spy_buyhold"] = {}
    results["qqq_buyhold"] = {}
    for window_name, (start, end) in WINDOWS.items():
        results["spy_buyhold"][window_name] = buyhold_metrics(prices, "SPY", start, end)
        results["qqq_buyhold"][window_name] = buyhold_metrics_from_closes(regime_df["QQQ"], start, end)

    tasks = [
        (cname, window_name, prices, regime_df, start, end, gseries)
        for window_name, (start, end) in WINDOWS.items()
        for cname, gseries in sorted(contenders.items())
    ]

    n_workers = min(8, max(1, (mp.cpu_count() or 2) - 2))
    print(f"\n=== Running {len(tasks)}-cell grid across {n_workers} workers ===", file=sys.stderr)
    t4 = time.time()
    with mp.Pool(n_workers) as pool:
        cell_results = pool.map(_run_one, tasks)  # deterministic: pool.map preserves task order
    t_grid = time.time() - t4

    for cname, window_name, m in cell_results:
        results[cname][window_name] = m

    print(
        f"\nWall-clock: fetch_prices={t_fetch_prices:.0f}s fetch_regime={t_fetch_regime:.0f}s "
        f"detectors={t_detectors:.0f}s sanity={t_sanity:.0f}s grid={t_grid:.0f}s "
        f"total={time.time()-t0:.0f}s",
        file=sys.stderr,
    )
    NOTES.append(
        f"Wall-clock by stage: fetch_prices={t_fetch_prices:.0f}s, fetch_regime_inputs={t_fetch_regime:.0f}s, "
        f"build_detector_series={t_detectors:.0f}s, sanity_checks={t_sanity:.0f}s, "
        f"full_grid ({len(tasks)} cells, {n_workers} workers)={t_grid:.0f}s."
    )

    NOTES.extend([
        "a2_baseline reuses a2_replay.py's exact engine construction (no-TLT universe, DualMomentumStrategy "
        "lookback_months=12, switch_threshold=0.02, pilot_entry_enabled=False, calm_market_hold_threshold=0.0, "
        "min_hold_enabled=False, use_ai=False, daily cadence, 0.1% transaction cost).",
        "Gate mechanism identical across gated contenders: risk_off sets equity_to_defensive_threshold=0.02 "
        "(easy exit) and defensive_to_equity_threshold=0.15 (hard re-entry); risk_on uses live defaults "
        "(0.15/0.05); mixed holds the previous day's gate state (hysteresis) to avoid flapping. Thresholds "
        "are mutated on the live DualMomentumStrategy instance immediately before each day's generate_signal() "
        "call — no src/aurel2/ source was modified.",
        "LT-heuristic detector (a2_gate_lt) is a narrowed adaptation of live-trader's daily_runner.py "
        "infer_regime(): original RISK_ASSETS={SPY,QQQ,IWM,EFA,EEM,XLE}, DEFENSIVE={GLD,TLT}; this script only "
        "fetches SPY/QQQ/GLD, so breadth is computed over {SPY,QQQ} (denominator 2, not 6) and defensive "
        "leadership uses GLD only (no TLT). This is a lower-fidelity breadth signal than live-trader's actual "
        "6-asset breadth — a caveat on how directly a2_gate_lt's numbers reflect live-trader's real detector.",
        "trend-vol detector (a2_gate_trendvol): risk_off requires SPY close < 200dma AND 20-day realized vol "
        "(annualized) above its trailing-252-trading-day 80th percentile; risk_on requires SPY close > 200dma; "
        "else mixed. All three inputs (close, 200dma, vol20, vol_pct80) are read as of the prior trading day's "
        "close relative to the decision day, matching the no-lookahead rule used for all detectors.",
        "HMM detector (a2_gate_hmm): 2-state Gaussian HMM (hmmlearn, diag covariance) on SPY daily log returns. "
        "Walk-forward with expanding window, refit on the first trading day of each new calendar month using "
        "all returns strictly before that day. Between refits the previously-fit model is reused. State "
        "inference for day D uses Viterbi decoding (predict()) over returns strictly before D (i.e. through "
        "D-1's close) — D's own return is never available to the model that labels D, since D's return isn't "
        "realized until D's close, the same close used to execute D's trade. risk_off = the state with the "
        "lower fitted mean return is the currently-inferred state.",
        "Detection-lag diagnostics measure, from a fixed reference date (2022-01-03 for the rate-hike bear; "
        "2020-03-23 for the COVID window), the number of trading days until each gated contender's hysteresis "
        "gate first reads risk_off on/after that date. The COVID window here starts at 2020-03-23 (the V-shape "
        "recovery start per the task brief), which is AFTER the crash's actual trough (2020-03-23 is close to "
        "the S&P 500 bottom) — so 'detection_lag' in that window measures how fast each detector confirms "
        "risk_off during the tail of the crash / early recovery chop, not the initial crash detection (Feb "
        "2020 is outside this window by construction).",
        f"Regime input data (SPY/QQQ/GLD) and all A2 universe symbols: yfinance auto-adjusted daily closes "
        f"via aurel2's CachedPriceProvider (universe) and a direct yfinance pull (regime detector inputs), "
        f"fetched from {FETCH_START} to warm the 200dma/HMM/vol-percentile lookbacks.",
        "No lookahead by construction: every detector's state for day D is computed from data with timestamp "
        "< D (previous close or earlier). The gate then applies that state's thresholds before D's "
        "generate_signal() call, so D's decision is made without knowledge of D's own price action.",
        "full_15y and 5y windows run the full daily-cadence engine loop, which is the slow path (thousands "
        "of trading days x orchestrator/strategy calls x 4 contenders); wall-clock noted in stderr per run.",
    ])

    out = {
        "generated_at": pd.Timestamp.utcnow().isoformat(),
        "windows": {k: {"start": v[0].isoformat(), "end": v[1].isoformat()} for k, v in WINDOWS.items()},
        "results": results,
        "notes": NOTES,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, indent=2, default=str))
    print(f"\nWrote {OUT_PATH} ({time.time()-t0:.0f}s total)", file=sys.stderr)


if __name__ == "__main__":
    main()
