"""Base classes for trading strategies.

This module provides the abstract base class and data structures that all
strategy implementations must follow.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from typing import Any

import pandas as pd

from aurel2.core.models import AssetClass, SignalAction


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy.

    Attributes:
        strategy_name: Name of the strategy that generated this signal.
        date: Date the signal was generated for.
        action: The recommended action (BUY, SELL, HOLD).
        asset_class: The asset class to trade, or None if no specific asset.
        confidence: Confidence level from 0.0 (lowest) to 1.0 (highest).
        reasoning: Human-readable explanation for the signal.
        metadata: Additional strategy-specific data.
    """

    strategy_name: str
    date: date
    action: SignalAction
    asset_class: AssetClass | None
    confidence: float
    reasoning: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the signal to a dictionary.

        Returns:
            Dictionary representation suitable for JSON serialization.
        """
        return {
            "strategy_name": self.strategy_name,
            "date": self.date.isoformat(),
            "action": self.action.value,
            "asset_class": self.asset_class.value if self.asset_class else None,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "metadata": self.metadata,
        }


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    All strategy implementations must inherit from this class and implement
    the abstract methods.

    Class Attributes:
        name: Unique identifier for the strategy. Must be defined by subclasses.
    """

    name: str

    def __init_subclass__(cls, **kwargs: Any) -> None:
        """Ensure subclasses define a name."""
        super().__init_subclass__(**kwargs)
        # Check if name is defined as a concrete value (not just a type annotation)
        # __annotations__ contains type hints, we need actual class attributes
        has_name = "name" in cls.__dict__ and isinstance(cls.__dict__["name"], str)
        if not has_name:
            # Only raise if this is a concrete class (no abstract methods)
            if not getattr(cls, "__abstractmethods__", set()):
                raise TypeError(
                    f"Strategy class {cls.__name__} must define a 'name' class attribute"
                )

    @abstractmethod
    def generate_signal(
        self,
        prices: pd.DataFrame,
        calc_date: date,
        current_holding: AssetClass | None,
    ) -> StrategySignal:
        """Generate a trading signal based on market data.

        Args:
            prices: DataFrame with historical price data. Index should be dates,
                columns should be asset symbols.
            calc_date: The date to generate the signal for.
            current_holding: The currently held asset class, or None if no position.

        Returns:
            A StrategySignal with the recommended action.
        """
        ...

    @abstractmethod
    def get_rebalance_dates(
        self,
        start_date: date,
        end_date: date,
    ) -> list[date]:
        """Get the dates when the strategy should be evaluated.

        Args:
            start_date: Start of the period.
            end_date: End of the period.

        Returns:
            List of dates when generate_signal should be called.
        """
        ...
